### ISSUE TITLE
can not build the protobuf files

### ISSUE THREAD

**Issue by iamhuyunlong** [bgshih/aster#101]
protos/preprocessor.proto:8:31: Expected field name.
protos/eval.proto: Import "Chinese_aster/protos/preprocessor.proto" was not found or had errors.
protos/eval.proto:55:12: "PreprocessingStep" is not defined.
I searched this error on the Internat, but can't get any helpful information.
I used protobuf 3.5

**Comment by Cabbagehust2507** [comment]
@iamhuyunlong Maybe because you change the name of folder from "aster" to "Chinese_aster". So if you want to build, you will have 2 choices:
1. Keep everything the same like original when you clone.
2. When you change your name's folder: you need to change the comand and export PYTHONPATH to your folder. 
I hope it can help you. :)

**Comment by iamhuyunlong** [comment]
> @iamhuyunlong也许是因为您将文件夹的名称从“ aster”更改为“ Chinese_aster”。因此，如果要构建，将有2个选择：
> 
> 1. 克隆时，请保持原始内容不变。
> 2. 更改名称的文件夹时：您需要更改命令并将PYTHONPATH导出到您的文件夹。
>    希望对您有所帮助。:)

thx, i've solved it.
